name: Deploy to Hugging Face Space
on:
  workflow_dispatch:

jobs:
  check-tests:
    runs-on: ubuntu-latest
    outputs:
      tests-passed: ${{ steps.check.outputs.passed }}
    steps:
      - name: Check latest test run
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'tests.yml',
              branch: context.ref.replace('refs/heads/', ''),
              per_page: 1
            });

            if (runs.workflow_runs.length === 0) {
              core.setFailed('No test runs found');
              return;
            }

            const latestRun = runs.workflow_runs[0];
            console.log(`Latest test run: ${latestRun.html_url}`);
            console.log(`Status: ${latestRun.status}`);
            console.log(`Conclusion: ${latestRun.conclusion}`);

            if (latestRun.conclusion !== 'success') {
              core.setFailed(`Tests did not pass. Status: ${latestRun.conclusion}`);
            } else {
              console.log('Tests passed successfully!');
              core.setOutput('passed', 'true');
            }
  deploy:
    needs: check-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git clone https://user:$HF_TOKEN@huggingface.co/spaces/Tapocheck77/nlp_suicide_watch space
          rsync -av --delete \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='data' \
            --exclude='space' \
            ./ space/
          cd space
          git lfs install || true
          if [[ -z $(git status -s) ]]; then
            echo "No changes to deploy"
            exit 0
          fi
          git add .
          git commit -m "Deploy from GitHub Actions [$(date +'%Y-%m-%d %H:%M:%S')]"
          git push origin main
