name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3.12-dev
        sudo apt-get install libhunspell-dev
        sudo apt-get install hunspell-en-us
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download spaCy model
      run: python -m spacy download en_core_web_sm

    - name: Run tests
      run: |
        pytest
