name: Run Tests

on: [push, pull_request]

jobs:
  build:
    uses: ./.github/workflows/docker-build.yml
    with:
      env: test
      lfs: false
    secrets: inherit

  run-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: docker run nlp_suicide_watch:test pytest
